### ISSUE TITLE
probe#restore_vim_state clobbers per-tab working directory?

### ISSUE THREAD

**Issue by campbellr** [torbiak/probe#14]
For some background, I started using vim tabs to separate projects that i am working (eg: tab A is for project Foo, in `~/git/foo`, tab B contains windows for project Bar, in `~/git/bar`). I set the working directory for each project using `:tcd`)

This works well, but I noticed that whenever I used `probe`, it would for some reason clobber the tab-specific working directory with the working directory of whatever tab I called `:Probe` from.

I think I tracked it down to this bit of code:

```
function! probe#restore_vim_state()
    cal s:restore_options()
    let @" = s:unnamed_register
    let @/ = s:last_pattern
    if s:orig_working_dir != ''
        exe printf('cd %s', s:orig_working_dir)
    endif

```

It uses `cd`, and i think ideally it should use `tcd`, although I don't actually know enough to say whether or not that would break anyone elses workflow...

Thoughts?

**Comment by campbellr** [comment]
Ok, I tried changing that call to use `tcd` instead, and it didn't fix it, so I'm not sure what's going on

**Comment by torbiak** [comment]
Sorry for the delay, Ryan. The fix was easy.

**Comment by campbellr** [comment]
Works like a charm, thanks! Looking at the diff, I'm a little embarrassed I wasn't able to figure out how get it working myself 😛 

I owe you a beer 🍻
