### ISSUE TITLE
Probe thinks my repo_root is my home directory

### ISSUE THREAD

**Issue by campbellr** [torbiak/probe#9]
When I run `:Probe` outside of a vcs repository (but under my home directory) it ends up scanning everything under `~/` instead of just under my current working directory (like i would have expected).

After some digging, it looks like this is because I have file (`/home/ryan/.bzr.log`) that is accidentally getting matched against `metadir_pattern` ( `\v/\.(git|hg|svn|bzr)>`).

If i understand vim patterns (which i don't), `>` matches the end of a word, which doesn't include periods

I made the following change that seems to work:

```diff
diff --git a/autoload/probe/file.vim b/autoload/probe/file.vim
index 5c43a7e..e6aeba8 100644
--- a/autoload/probe/file.vim
+++ b/autoload/probe/file.vim
@@ -138,7 +138,7 @@ function! s:cache_filepath()
 endfunction
 
 function! s:find_metadir()
-    let metadir_pattern = '\v/\.(git|hg|svn|bzr)>'
+    let metadir_pattern = '\v/\.(git|hg|svn|bzr)\n'
     let orig_dir = getcwd()
     let dir = orig_dir
     while 1
```

I'd submit this as a pull request if i was more confident that this change doesn't break something else...

**Comment by torbiak** [comment]
It used to look for `\n`, actually, before 74d5305d. I have no idea why I changed it, since `glob()` and `globpath()` explicitly return a string of paths separated by newlines.

**Comment by campbellr** [comment]
Cool, thanks!
